controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_producto_search:
    path: /search
    controller: App\Controller\ProductoController::buscarProductos
